namespace UnitsLogger_BepInEx
{
    public enum DataType
    {
        Null,
        Names,
        ReceivedTraits,
        LostTraits,
        ReceivedItems,
        LostItems,
        Children,
        Professions,
        Сitizenships,
        Townships,
        Culturships,
        Moods,
        Food,
        KilledUnits,
        ManufacturedItem,
        SocialCharacteristics,
        GetResources,
        GiveResources,
        NewEra,
        CitizenJobStart,
        CitizenJobEnd,
        BuildedConstruction,
        CleanedConstruction,
        ExtractResources
    }
}
